use_gpu: true

whisper:
  model_size: small      # small = fast; bump to medium later if quality needs it

clip:
  min_seconds: 15
  max_seconds: 45
  buffer_in: 0.25
  buffer_out: 0.35

scoring:
  mode: hybrid           # local hooks + audio peaks, then GPT ordering
  max_clips: 5
  window_sec: 10
  stride_sec: 5
  gpt_model: gpt-4o-mini

encode:
  mode: nvenc
  width: 1080
  height: 1920
  fps: 60
  rc: vbr_hq
  cq: 19
  b_v: 8M
  maxrate: 12M
  bufsize: 24M
  preset: p5
  profile: high
  gop: 120
  aq: 1
  aq_strength: 8
  bf: 3
  audio_bitrate: 192k
  audio_rate: 48000
  pad_in: 0.15
  pad_out: 0.20

captions:
  font: Arial
  font_size: 38
  outline: 3
  margin_v: 110
