use_gpu: true

scoring:
  mode: hybrid   # local + GPT mixing
  max_clips: 5
  window_sec: 10
  stride_sec: 5
clip:
  min_seconds: 15
  max_seconds: 45
  buffer_in: 0.25
  buffer_out: 0.35


captions:
  style: outlined
  font: Arial.ttf
  size_ratio: 0.06
  emoji: false


reframe:
  enable_face_track: false
  min_face_conf: 0.5
