use_gpu: false

scoring:
  mode: hybrid   # local + GPT mixing
  max_clips: 5
  window_sec: 10
  stride_sec: 5
clip:
  min_seconds: 15
  max_seconds: 45
  buffer_in: 0.25
  buffer_out: 0.35

whisper:
  model_size: medium         # small / medium / large-v3
  beam_size: 1               # 1 = fastest
  vad_filter: true
  vad_parameters:
    min_silence_duration_ms: 500
  compute_type_gpu: float16  # best on 40xx
  compute_type_cpu: int8     # fast on CPU

captions:
  style: outlined
  font: Arial.ttf
  size_ratio: 0.06
  emoji: false


reframe:
  enable_face_track: false
  min_face_conf: 0.5

encode:
  mode: nvenc
  crf: 23
  preset: p5
  audio_bitrate: 128k

